### ISSUE TITLE
You could build AssemblyScript more efficiently

### ISSUE THREAD

**Issue by MaxGraey** [dirkschumacher/polyglotr#1]
Just add `--runtime none` or `--runtime half` to [build command](https://github.com/dirkschumacher/polyglotr/blob/master/devel/assemblyscript/fib.ts#L1):
```
asc fib.ts -b fib.wasm -O3 --runtime none
```
It will produce module with size `116 bytes` instead `5.5 КБ`.

But most strange thing is how AS could be so slower Rust for example if they both have pretty same `fib` code if we decoded it to wat?

Rust:
```wat
(func $rustc_h_6i5ti3eejgt::fib::h3cf8ce26e02a59ad (type $t0) (param $p0 i32) (result i32)
    block $B0
      get_local $p0
      i32.const 3
      i32.ge_s
      br_if $B0
      get_local $p0
      return
    end
    get_local $p0
    i32.const -1
    i32.add
    call $rustc_h_6i5ti3eejgt::fib::h3cf8ce26e02a59ad
    get_local $p0
    i32.const -2
    i32.add
    call $rustc_h_6i5ti3eejgt::fib::h3cf8ce26e02a59ad
    i32.add)
```

AS:
```wat
(func $fib (export "fib") (type $t4) (param $p0 i32) (result i32)
    get_local $p0
    i32.const 2
    i32.lt_s
    if $I0
      get_local $p0
      return
    end
    get_local $p0
    i32.const 1
    i32.sub
    call $fib
    get_local $p0
    i32.const 2
    i32.sub
    call $fib
    i32.add)
```

**Comment by dirkschumacher** [comment]
Nice thanks 👍 Will take a look later

**Comment by dirkschumacher** [comment]
Most of the time is surely spent outside of wasm. E.g. loading and parsing. Will update once I have a computer again and time.

**Comment by MaxGraey** [comment]
My simple bench in WebAssembly Studio give me same bench result for AS and C in latest Chrome anf Firefox:
https://webassembly.studio/?f=1snzpad6xrj

<img width="220" alt="Снимок экрана 2019-08-30 в 12 55 01" src="https://user-images.githubusercontent.com/1301959/64011992-780f2e00-cb25-11e9-8c54-44cfadb7b875.png">

Wasmer (Cranelift) should job even better

**Comment by dirkschumacher** [comment]
Updated the binary. Thanks

**Comment by MaxGraey** [comment]
Thanks! Add plz `--runtime none` to [comment here](https://github.com/dirkschumacher/polyglotr/blob/master/devel/assemblyscript/fib.ts#L1)

**Comment by dirkschumacher** [comment]
Done
